project_id = "vmracacpxlpnpsxfokty"

[functions.send-program-registration]
verify_jwt = false

[functions.send-imam-query]
verify_jwt = false

[functions.verify-turnstile]
verify_jwt = false

[functions.send-feedback]
verify_jwt = false

[functions.register-student]
verify_jwt = false

[functions.register-hifz-student]
verify_jwt = false

[functions.address-lookup]
verify_jwt = false

[functions.send-maktab-registration]
verify_jwt = false

[functions.send-contact-confirmation]
verify_jwt = false

[functions.emasjid-live-status]
verify_jwt = false

[functions.get-turnstile-site-key]
verify_jwt = false

[functions.push-subscribe]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.get-vapid-public-key]
verify_jwt = false

[functions.check-live-and-notify]
verify_jwt = false
